# nmap parameters
nmap:
  # Standard nmap arguments
  arguments: '-sT'
  # Ports to scan
  ports: '1-65535'
  # Timeout for each scan (one host)
  timeout: ~
scanner:
  # Array of hostnames, ip addresses or CIDR
  hosts:
    - '127.0.0.1/24'
  # Number of nmap process to run in parallel
  parallel: 10